#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 翻页
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Test")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertUSERS1(USERS1 instance);
    partial void UpdateUSERS1(USERS1 instance);
    partial void DeleteUSERS1(USERS1 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::翻页.Properties.Settings.Default.TestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<USERS1> USERS1
		{
			get
			{
				return this.GetTable<USERS1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERS1")]
	public partial class USERS1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERS1_ID;
		
		private string _USERS1_NAME;
		
		private string _USERS1_SAX;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERS1_IDChanging(string value);
    partial void OnUSERS1_IDChanged();
    partial void OnUSERS1_NAMEChanging(string value);
    partial void OnUSERS1_NAMEChanged();
    partial void OnUSERS1_SAXChanging(string value);
    partial void OnUSERS1_SAXChanged();
    #endregion
		
		public USERS1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERS1_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERS1_ID
		{
			get
			{
				return this._USERS1_ID;
			}
			set
			{
				if ((this._USERS1_ID != value))
				{
					this.OnUSERS1_IDChanging(value);
					this.SendPropertyChanging();
					this._USERS1_ID = value;
					this.SendPropertyChanged("USERS1_ID");
					this.OnUSERS1_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERS1_NAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USERS1_NAME
		{
			get
			{
				return this._USERS1_NAME;
			}
			set
			{
				if ((this._USERS1_NAME != value))
				{
					this.OnUSERS1_NAMEChanging(value);
					this.SendPropertyChanging();
					this._USERS1_NAME = value;
					this.SendPropertyChanged("USERS1_NAME");
					this.OnUSERS1_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERS1_SAX", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USERS1_SAX
		{
			get
			{
				return this._USERS1_SAX;
			}
			set
			{
				if ((this._USERS1_SAX != value))
				{
					this.OnUSERS1_SAXChanging(value);
					this.SendPropertyChanging();
					this._USERS1_SAX = value;
					this.SendPropertyChanged("USERS1_SAX");
					this.OnUSERS1_SAXChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
